import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_sections/Header";
import Footer from "./_sections/Footer";
import { Divider } from "@mui/material";
import { ToastContainer, Bounce } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inventory Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <ToastContainer
      position="top-center"
      autoClose={5000}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      theme="light"
      transition= {Bounce}/>
        <main>
          {children}
        </main>
        <Divider sx={{ my: '10px', pt: '4px', position: 'fixed', bottom: '60px', width: '100%', zIndex: 5 }} />
        <Footer/>
      </body>
    </html>
  );
}
