import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_sections/Header";
import Footer from "./_sections/Footer";
import { Divider, linkClasses } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inventory Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
        <main>
          {children}
        </main>
        <Divider sx={{ my: '10px', pt: '4px', position: 'fixed', bottom: '60px', width: '100%' }} />
        <Footer/>
      </body>
    </html>
  );
}
